import { screens } from "@/shared/token";
import { StyleSheet } from "react-native";

export const WelcomePageStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  page: {
    height: screens.height * 0.79,
    width: screens.width,
    justifyContent: "flex-end",
  },
  img: {
    height: screens.height * 0.5,
    width: screens.width - screens.width * 0.15,
    position: "absolute",
    top: "8%",
    left: "50%",
    transform: [{ translateX: "-50%" }],
    borderBottomRightRadius: 30,
    borderBottomLeftRadius: 30,
    borderRadius: 30,
    elevation: 20,
  },
  gradient: {
    position: "absolute",
    height: screens.height * 0.5,
    width: screens.width,
    zIndex: 1,
    top: 0,
  },
  buttonText: {
    fontSize: 16,
  },
  contentBox: {
    paddingHorizontal: screens.width * 0.04,
    zIndex: 2,
    gap: 10,
  },
  mainButtonBox: {
    height: screens.height * 0.15,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    overflow: "hidden",
    padding: 5,
    paddingTop: screens.width * 0.04,
    paddingHorizontal: screens.width * 0.04,
  },
  mainButton: {
    height: 75,
    borderRadius: 30,
    elevation: 10,
    justifyContent: "center",
    alignItems: "center",
    overflow: "hidden",
  },
  mainButtonText: {
    fontSize: 18,
    letterSpacing: 1,
    fontWeight: 500,
  },
  langButton: {
    position: "absolute",
    top: 40,
    left: 2,
    height: 40,
    width: 60,
    borderTopLeftRadius: 5,
    borderBottomLeftRadius: 5,
    borderTopRightRadius: 20,
    borderBottomRightRadius: 20,
    elevation: 10,
    overflow: "hidden",
    padding: 3,
  },
  langButtonBox: {
    width: "100%",
    height: "100%",
    justifyContent: "center",
    alignItems: "center",
    borderTopLeftRadius: 3,
    borderBottomLeftRadius: 3,
    borderTopRightRadius: 18,
    borderBottomRightRadius: 18,
    borderWidth: 2,
    paddingRight: 3,
  },
  langButtonText: {
    fontWeight: 500,
    letterSpacing: 2,
  },
  back: {
    position: "absolute",
    height: 65,
    width: 65,
    left: 5,
    top: "50%",
    transform: [{ translateY: "-50%" }],
    borderTopLeftRadius: 25,
    borderBottomLeftRadius: 25,
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    padding: 5,
    paddingLeft: 5,
    justifyContent: "center",
    alignItems: "center",
  },
  dotesBox: {
    position: "absolute",
    bottom: screens.height * 0.419,
    left: "50%",
    transform: [{ translateX: "-50%" }],
    zIndex: 3,
    flexDirection: "row",
    gap: 5,
  },
  dotes: {
    height: 3,
    borderRadius: 10,
    elevation: 5,
  },
});
